name: seeker_ng
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependency_overrides:
  intl: ^0.18.0
  wakelock: ^0.6.2
  win32: ^4.1.3
  package_info_plus: ^3.1.2

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.0.0
  cashfree_pg: ^2.0.10+30
  colorlizer: ^0.0.4
  connectivity: ^3.0.6
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  dio: ^4.0.6
  expandable: ^5.0.1
  file_picker:
  file:
  # firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_date_pickers: ^0.3.0
  flutter_facebook_auth: ^4.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.1.0
  flutter_stripe: ^3.2.0
  flutter_svg: ^1.0.3
  flutter_widget_from_html: ^0.8.5
  fluttertoast: ^8.0.9
  flutterwave_standard: ^1.0.3
  flutterzilla_fixed_grid: ^0.0.4
  google_sign_in: ^5.3.0
  http_auth: ^1.0.1
  image_picker: ^0.8.5
  intl: ^0.18.0
  intl_phone_field: ^3.1.0
  line_awesome_flutter: ^2.0.0
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  pin_code_fields: ^7.4.0
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  pusher_beams: ^1.1.1
  pusher_channels_flutter: ^2.0.1
  razorpay_flutter: ^1.3.0
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.0.13
  sliding_up_panel: ^2.0.0+1
  sqflite: ^2.0.2+1
  step_progress_indicator: ^1.0.2
  top_snackbar_flutter: ^1.1.1
  url_launcher: ^6.1.6
  uuid: ^3.0.6
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.0.0
  flutter_local_notifications: ^12.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/payment/
    - assets/svg/
