var appStrings = {
  "welcome": "welcome",
  "Browse categories": "Browse categories",
  "All categories": "All categories",
  "Top services": "Top services",
  "Recently listed": "Recently listed",
  "See all": "See all",
  "Home": "Home",
  "Orders": "Orders",
  "Save": "Save",
  "Saved": "Saved",
  "Search": "Search",
  "Settings": "Settings",
  "Search services": "Search services",
  "Date": "Date",
  "Schedule": "Schedule",
  "Billed": "Billed",
  "My orders": "My orders",
  "Seller Details": "Seller Details",
  "Name": "Name",
  "Email": "Email",
  "Phone": "Phone",
  "Post Code": "Post Code",
  "Address": "Address",
  "Date & Schedule": "Date & Schedule",
  "Amount Details": "Amount Details",
  "Package fee": "Package fee",
  "Extra service": "Extra service",
  "Subtotal": "Subtotal",
  "Tax": "Tax",
  "Total": "Total",
  "Payment status": "Payment status",
  "Order Status": "Order Status",
  "Saved Services": "Saved Services",
  "Starts from": "Starts from",
  "No result found": "No result found",
  "Pending orders": "Pending orders",
  "Active orders": "Active orders",
  "Completed orders": "Completed orders",
  "Total orders": "Total orders",
  "City": "City",
  "Area": "Area",
  "Country": "Country",
  "Support ticket": "Support ticket",
  "Edit profile": "Edit profile",
  "Change Password": "Change Password",
  "Logout": "Logout",
  "Create": "Create",
  "No ticket": "No ticket",
  "All services": "All services",
  "All": "All",
  "Highest price": "Highest price",
  "Lowest price": "Lowest price",
  "Latest service": "Latest service",
  "Full Name": "Full Name",
  "About": "About",
  "Your Address": "Your Address",
  "Choose country": "Choose country",
  "Choose city": "Choose city",
  "Choose Area": "Choose Area",
  "Service Name": "Service Name",
  "Our Package": "Our Package",
  "Orders Completed": "Orders Completed",
  "Seller ratings": "Seller ratings",
  "Overview": "Overview",
  "About Seller": "About Seller",
  "Review": "Review",
  "Benefits of premium Package": "Benefits of premium Package",
  "Benefits of the premium package": "Benefits of the premium package",
  "FAQ": "FAQ",
  "Book appointment": "Book appointment",
  "Personalize": "Personalize",
  "Service personalization": "Service personalization",
  "Next": "Next",
  "What's included": "What's included",
  "Add Extra": "Add Extra",
  "Benefits of the package": "Benefits of the package",
  "Benefits of the Package": "Benefits of the Package",
  "Available Schedules": "Available Schedules",
  "Available time": "Available time",
  "No schedule available on this date": "No schedule available on this date",
  "Choose Location": "Choose Location",
  "Booking information's": "Booking information's",
  "Booking confirmation": "Booking confirmation",
  "Booking Details": "Booking Details",
  "Location": "Location",
  "Swipe up for details": "Swipe up for details",
  "Proceed to payment": "Proceed to payment",
  "Collapse details": "Collapse details",
  "Appointment package service": "Appointment package service",
  "Extra service fee": "Extra service fee",
  "Coupon": "Coupon",
  "Coupon code": "Coupon code",
  "Enter coupon code": "Enter coupon code",
  "Apply": "Apply",
  "Payment": "Payment",
  "Total payable": "Total payable",
  "Choose payment method": "Choose payment method",
  "Choose images": "Choose images",
  "I agree with the terms and conditions":
      "I agree with the terms and conditions",
  "Pay & confirm order": "Pay & confirm order",
  "Payment successful": "Payment successful",
  "Order status": "Order status",
  "Are you sure?": "Are you sure?",
  "Cancel": "Cancel",
  "Welcome back! Login": "Welcome back! Login",
  "Password": "Password",
  "Remember me": "Remember me",
  "Forgot Password?": "Forgot Password?",
  "Login": "Login",
  "Enter password": "Enter password",
  "Do not have an account": "Do not have an account",
  "Register": "Register",
  "Or": "Or",
  "Login with google": "Login with google",
  "Login with facebook": "Login with facebook",
  "Register to join us": "Register to join us",
  "Enter your full name": "Enter your full name",
  "Enter your username": "Enter your username",
  "Enter your email": "Enter your email",
  "Continue": "Continue",
  "Already have an account": "Already have an account",
  "Repeat password": "Repeat password",
  "Phone number": "Phone number",
  "Reset password": "Reset password",
  "Enter the email you used to create account and we well send information for resetting password":
      "Enter the email you used to create account and we well send information for resetting password",
  "Enter email": "Enter email",
  "Send instructions": "Send instructions",
  "Enter the 4 digit code": "Enter the 4 digit code",
  "Enter the 4 digit code we sent to your email in order to reset password":
      "Enter the 4 digit code we sent to your email in order to reset password",
  "Did not receive": "Didn't receive",
  "Send again": "Send again",
  "Something went wrong": "Something went wrong",
  "Please wait while the profile is updating":
      "Please wait while the profile is updating",
  "Please enter your email": "Please enter your email",
  "Please enter post code": "Please enter post code",
  "You must select a state and area": "You must select a state and area",
  "Address field is required": "Address field is required",
  "Phone field is required": "Phone field is required",
  "Updating profile...It may take few seconds":
      "Updating profile...It may take few seconds",
  "You must agree with the terms and conditions to register":
      "You must agree with the terms and conditions to register",
  "Password did not match": "Password did not match",
  "Password must be at least 6 characters":
      "Password must be at least 6 characters",
  "Have an account": "Have an account",
  'Menu': 'Menu',
  "My jobs": "My jobs",
  "Job requests": "Job requests",
  "Support Ticket": "Support Ticket",
  "Wallet": "Wallet",
  "My report list": "My report list",
  "Edit Profile": "Edit Profile",
  "Change password": "Change password",
  "Enter current password": "Enter current password",
  "Enter your current password": "Enter your current password",
  "Please enter your password": "Please enter your password",
  "Repeat new password": "Repeat new password",
  "Please retype your password": "Please retype your password",
  "Retype new password": "Retype new password",
  "Make sure you repeated new password correctly":
      "Make sure you repeated new password correctly",
  "Password changed successfully": "Password changed successfully",
  "Please turn on your internet connection":
      "Please turn on your internet connection",
  "Your entered the otp correctly but something went wrong. Please try again later":
      "Your entered the otp correctly but something went wrong. Please try again later",
  "Otp didn't match": "Otp didn't match",
  "Otp is null": "Otp is null",
  "Didn't get any user info after google sign in. visit google sign in service file":
      "Didn't get any user info after google sign in. visit google sign in service file",
  "Login successful": "Login successful",
  "Invalid Email or Password": "Invalid Email or Password",
  "Password didn't match": "Password didn't match",
  "Password updated successfully": "Password updated successfully",
  "Registration successful": "Registration successful",
  "Otp send failed": "Otp send failed",
  "You already applied this coupon": "You already applied this coupon",
  "Please enter a valid coupon": "Please enter a valid coupon",
  "Order placed successfully": "Order placed successfully",
  "Failed to make payment status successful":
      "Failed to make payment status successful",
  "Check your internet connection and try again":
      "Check your internet connection and try again",
  "You have received an order from": "You have received an order from",
  "You must select an image": "You must select an image",
  "You must select category & subcategory":
      "You must select category & subcategory",
  "Job posted successfully": "Job posted successfully",
  "Job updated successfully": "Job updated successfully",
  "Only zip file is supported": "Only zip file is supported",
  "Please check your internet connection":
      "Please check your internet connection",
  "New job chat message": "New job chat message",
  "Hiring successful": "Hiring successful",
  "Job deleted successfully": "Job deleted successfully",
  "New chat message": "New chat message",
  "You don't have enough wallet balance":
      "You don't have enough wallet balance",
  "Payment cancelled": "Payment cancelled",
  "Service Personalization": "Service Personalization",
  "Information's": "Information's",
  "Booking Confirmations": "Booking Confirmations",
  "Select Country": "Select Country",
  "Select State": "Select State",
  "Select Area": "Select Area",
  "review posted successfully": "Review posted successfully",
  "Report submitted": "Report submitted",
  "accepted your order extra request": "accepted your order extra request",
  "Error accepting order extra": "Error accepting order extra",
  "Error declining order extra": "Error declining order extra",
  "accepted your order completion request":
      "accepted your order completion request",
  "Profile updated successfully": "Profile updated successfully",
  "Wallet deposit success": "Wallet deposit success",
  "You must enter an amount": "You must enter an amount",
  "Please enter a valid amount": "Please enter a valid amount",
  "Ticket created successfully": "Ticket created successfully",
  "Welcome": "Welcome",
  "Create Job": "Create Job",
  "Please enter a title": "Please enter a title",
  "Title": "Title",
  "Budget": "Budget",
  "Please enter your budget": "Please enter your budget",
  "Description": "Description",
  "End date": "End date",
  "Create job": "Create job",
  "You must enter a valid budget": "You must enter a valid budget",
  "Choose states": "Choose states",
  "Category": "Category",
  "Sub Category": "Sub Category",
  "Ratings": "Ratings",
  "Sort By": "Sort By",
  'Select Category': 'Select Category',
  'Select Subcategory': 'Select Subcategory',
  "Highest Price": "Highest Price",
  "Lowest Price": "Lowest Price",
  "Latest Service": "Latest Service",
  "Offline": "Offline",
  "Online": "Online",
  "Job Requests": "Job Requests",
  "View details": "View details",
  "Conversation": "Conversation",
  "Hire now": "Hire now",
  'Your offer': 'Your offer',
  "Seller offer": "Seller offer",
  "No request found": "No request found",
  'Deadline': 'Deadline',
  "Balance": "Balance",
  "History": "History",
  "Gateway": "Gateway",
  "Amount": "Amount",
  "Payment Status": "Payment Status",
  'No history found': 'No history found',
  "Total Payable": "Total Payable",
  "Deposit Amount": "Deposit Amount",
  "Enter deposit amount": "Enter deposit amount",
  "You must agree with the terms and conditions to place the order":
      "You must agree with the terms and conditions to place the order",
  "Pay & Confirm": "Pay & Confirm",
  "I agree with terms and conditions": "I agree with terms and conditions",
  "Reports": "Reports",
  "Report id": "Report id",
  'Chat admin': 'Chat admin',
  "Order id": "Order id",
  "No Report": "No Report",
  "Please write a message first": "Please write a message first",
  "Write message": "Write message",
  "Remember Me": "Remember Me",
  "Don't have account?": "Don't have account?",
  "Login with Google": "Login with Google",
  "Login with Facebook": "Login with Facebook",
  "Full name": "Full name",
  "Please enter your full name": "Please enter your full name",
  "Username": "Username",
  "Please enter your username": "Please enter your username",
  "Enter phone number": "Enter phone number",
  "Have an account?": "Have an account?",
  "Sign Up": "Sign Up",
  "Choose area": "Choose area",
  "Book Now": 'Book Now',
  "Recent jobs": 'Recent jobs',
  "Top booked services": 'Top booked services',
  "About seller": 'About seller',
  "Order Completed": 'Order Completed',
  "From": 'From',
  "Order Completion Rate": 'Order Completion Rate',
  "Seller Since": 'Seller Since',
  "Orders completed": 'Orders completed',
  "Seller Ratings": 'Seller Ratings',
  "Watch video": 'Watch video',
  "Book Appointment": 'Book Appointment',
  "What is included": 'What is included',
  "Add extras": 'Add extras',
  "Booking Information": 'Booking Information',
  "Details": 'Details',
  "Booking details": 'Booking details',
  "Package Fee": 'Package Fee',
  "Extra Service Fee": 'Extra Service Fee',
  "Extra Service": 'Extra Service',
  "My Orders": 'My Orders',
  "You can not cancel this order": 'You can not cancel this order',
  "No active order": 'No active order',
  "Leave feedback": 'Leave feedback',
  "Cancel order": 'Cancel order',
  "Report to admin": 'Report to admin',
  "Order Details": 'Order Details',
  "Payment method": 'Payment method',
  "Pay now": 'Pay now',
  "Saved services": 'Saved services',
  "No service saved": 'No service saved',
  "Payment failed!": 'Payment failed!',
  "Go to home": 'Go to home',
  "Personal information's": "Personal information's",
  "Your address": 'Your address',
  "Time": 'Time',
  "Active": 'Active',
  "Pending": 'Pending',
  "pending": 'pending',
  "Delivered": 'Delivered',
  "Completed": 'Completed',
  "complete": 'complete',
  "Cancelled": 'Cancelled',
  "Unknown": 'Unknown',
  "Decline history": 'Decline history',
  "Decline reason": 'Decline reason',
  "Buyer details": 'Buyer details',
  "Complete Request": 'Complete Request',
  "Declined": 'Declined',
  "Order completed": 'Order completed',
  "Seller requested to mark this order complete":
      'Seller requested to mark this order complete',
  "Decline": 'Decline',
  "Accept": 'Accept',
  "Skip": 'Skip',
  "Job Request ID": 'Job Request ID',
  "Attachment": 'Attachment',
  "Conversations": 'Conversations',
  "You don't have any active conversation":
      "You don't have any active conversation",
  "Write message...": "Write message...",
  "Edit": 'Edit',
  "Delete": 'Delete',
  "On/Off": 'On/Off',
  "Urgent": 'Urgent',
  "High": 'High',
  "Medium": 'Medium',
  "Low": 'Low',
  "Please enter ticket title": 'Please enter ticket title',
  "Ticket title": 'Ticket title',
  "Please explain your problem": 'Please explain your problem',
  "Create ticket": 'Create ticket',
  "You don't have any active order": "You don't have any active order",
  "open": 'open',
  "close": 'close',
  "Enter the email you used to create account and we'll send instruction for resetting password":
      "Enter the email you used to create account and we'll send instruction for resetting password",
  "Enter Email": "Enter Email",
  "Send Instructions": "Send Instructions",
  "All Categories": 'All Categories',
  "Already hired a seller for this job.":
      'Already hired a seller for this job.',
  "Enter the 4 digit code we sent to to your email in order to reset password":
      'Enter the 4 digit code we sent to to your email in order to reset password',
  "OR": 'OR',
  "Sign in": 'Sign in',
  "Search country": 'Search country',
  "Verify Email": 'Verify Email',
  "by": 'by',
  "Star": 'Star',
  "Write a review": 'Write a review',
  "How was the service?": "How was the service?",
  "Post review": "Post review",
  "Report": "Report",
  "What went wrong?": "What went wrong?",
  "Write the issue": "Write the issue",
  "Submit Report": "Submit Report",
  "You must write something to submit report":
      "You must write something to submit report",
  "Yes": "Yes",
  "No": "No",
  "Load Failed": "Load Failed",
  "Release to load more": "Release to load more",
  "No more Data": "No more Data",
  "Edit Job": "Edit Job",
  "Edit job": "Edit job",
  "Select area": "Select area",
  "New password": "New password",
  "Enter new password": "Enter new password",
  "No service available": "No service available",
  "No service available in your area": "No service available in your area",
  "No Date Created": "No Date Created",
  "No Schedule Created": "No Schedule Created",
  "Show Description": "Show Description",
  "Hide Description": "Hide Description",
  "Post code": "Post code",
  "All Services": "All Services",
  "Select Date": "Select Date",
  "Support tickets": "Support tickets",
  "Priority": "Priority",
  "Order number": "Order number",
  "Success": "Success",
  "Order extra accepted": "Order extra accepted",
  "Hired successfully": "Hired successfully",
  "January": "January",
  "February": "February",
  "March": "March",
  "April": "April",
  "Enter the 4 digit code we sent to to your email in order verify your email":
      "Enter the 4 digit code we sent to to your email in order verify your email",
  "Describe why you want to decline the request":
      "Describe why you want to decline the request",
  "You must enter decline reason": "You must enter decline reason",
  "Press again to exit": "Press again to exit",
  "Order complete request successfully approved.":
      "Order complete request successfully approved.",
  "No city found": "No city found",
  "Search state": "Search state",
  "Select City": "Select City",
  "No country found": "No country found",
  "No area found": "No area found",
  "Search area": "Search area",
  "Choose image": "Choose image",
  "Unit price": "Unit price",
  "Quantity": "Quantity",
  "declined your order extra request": "declined your order extra request",
  "Order Id": "Order Id",
  "Decline Success": "Decline Success",
  "Extra Service Not Found": "Low",
  "No date found": "No date found",
  "Delete Account": "Delete Account",
  "active": "active",
  "delivered": "delivered",
  "cancelled": "cancelled",
  "Order Not Found": "Order Not Found",
  "Support Ticket Created Success": "Support Ticket Created Success",
  "Message:": "Message:",
  "Password Change Unavailable. We're sorry, but users who have signed up or logged in using their Google or Facebook accounts do not have the option to change their password directly on this platform.":
      "Password Change Unavailable. We're sorry, but users who have signed up or logged in using their Google or Facebook accounts do not have the option to change their password directly on this platform.",
  "Payment cancelled!": "Payment cancelled!",
  "Payment has been expired.": "Payment has been expired.",
  "Payment has been cancelled.": "Payment has been cancelled.",
  "Welcome to Seekers.Ng": "Welcome to Seekers.Ng",
  "Hello! 👋": "Hello! 👋",
  "You'll have to login/register to edit or see your profile info.":
      "You'll have to login/register to edit or see your profile info.",
  "Sign-In/Sign-Up": "Sign-In/Sign-Up",
  "Sign in with Apple": "Sign in with Apple",
  "Apple id revoked successfully": "Apple id revoked successfully",
  "Apple id revoke failed": "Apple id revoke failed",
  "Sign up": "Sign up",
  "Sign In": "Sign In",
  "Low": "Low",
  "Low": "Low",
  "Low": "Low",
  "Low": "Low",
  "Low": "Low",
  "Low": "Low",
};
